# Dockerfile extending the generic Node image with application files for a
# single application.
FROM gcr.io/google_appengine/nodejs
COPY package.json /app/
# Check to see if the the version included in the base runtime satisfies
# 6.9.1, if not then do an npm install of the latest available
# version that satisfies it.

#RUN npm install --global npm@3.10.8

# You have to specify "--unsafe-perm" with npm install
# when running as root.  Failing to do this can cause
# install to appear to succeed even if a preinstall
# script fails, and may have other adverse consequences
# as well.
# This command will also cat the npm-debug.log file after the
# build, if it exists.

RUN npm install --global npm@3.10.8 &&\
    /usr/local/bin/install_node 6.9.1 &&\
    npm install --production --unsafe-perm || \
    npm install -g gatsby@next && \
    ((if [ -f npm-debug.log ]; then \
        cat npm-debug.log; \
      fi) && false) && \
    npm uninstall npm -g

RUN mkdir -p /var/log/app_engine/custom_logs