FROM node:6.9.1
COPY package.json /postaldistrix-ci-install/

# You have to specify "--unsafe-perm" with npm install
# when running as root.  Failing to do this can cause
# install to appear to succeed even if a preinstall
# script fails, and may have other adverse consequences
# as well.
# This command will also cat the npm-debug.log file after the
# build, if it exists.

RUN npm install --global --quiet npm@3.10.8 && \
    cd /postaldistrix-ci-install && npm install --unsafe-perm --quiet || \
  ((if [ -f npm-debug.log ]; then \
      cat npm-debug.log; \
    fi) && false) && \
    npm install -g gatsby@next && \
    npm cache clean